-- CREAT DATABASE
CREATE DATABASE SOCIAL;
-- DELETE DATABASE
DROP DATABASE SOCIAL;
-- CREAT TABLE IN SOCIAL DATABASE
CREATE TABLE SOCIAL.USER(
  ID INT NOT NULL PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL,
  NAME VARCHAR(225),
  EMAIL VARCHAR(225),
  PHONE VARCHAR(11)
  )
--   UPDATE TABLE AND ADD ADDRESS IN SOCIAL
ALTER TABLE SOCIAL.USER ADD ADDRESS VARCHAR(225)
-- UPDATE ADDRESS TYPE
ALTER TABLE SOCIAL.USER MODIFY ADDRESS VARCHAR(150);
-- ADD VALUES IN TABLE
INSERT INTO SOCIAL.user (`ID`, `USERNAME`, `NAME`, `EMAIL`, `PHONE`, `ADDRESS`) VALUES ('1', 'iSRAR4040', 'iSRAR', 'MALIK4040', NULL, NULL);
-- DELETE SPECIFIC DATA FROM USER TABLE
DELETE FROM USER WHERE NAME='iSRAR';